FROM python:3.9

# it takes a minutes to insteall each one, so break up into smaller chuncks.
# WORKDIR /app

# https://pythonspeed.com/articles/activate-virtualenv-dockerfile/
ENV VIRTUAL_ENV=/opt/venv
# RUN python -m venv .venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# RUN source .venv/bin/activate
RUN pip install torch --extra-index-url https://download.pytorch.org/whl/cpu 
RUN pip install torchvision --extra-index-url https://download.pytorch.org/whl/cpu 
RUN pip install torchaudio --extra-index-url https://download.pytorch.org/whl/cpu 
RUN pip install opencv-python flask imageio


WORKDIR /app
# RUN pip install 'git+https://github.com/facebookresearch/detectron2.git'
RUN git clone https://github.com/facebookresearch/detectron2.git
RUN python -m pip install -e detectron2

# needed for opencv
RUN apt-get update
RUN apt-get install -y  libgl1-mesa-dev
