FROM python:3.9

ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV

# install torch and stuff
RUN pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

# install stuff for making a webserver and processing images
RUN pip install opencv-python flask imageio

# install the detection code for github
WORKDIR /detection
# Or, to install it from a local clone:
RUN git clone https://github.com/facebookresearch/detectron2.git
RUN python -m pip install -e detectron2

# needed for opencv
RUN apt-get update
RUN apt-get install -y  libgl1-mesa-dev